config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/") 
  root "home#index"

  # Devise routes for users (grouped together)
  devise_for :users

  # Your custom routes
  resources :posts, except: [:index]
  resources :reactions, only: [:create, :destroy]
  get '/posts', to: 'posts#index', as: 'user_root'
  get '/default_avatar', to: 'avatars#default', as: :default_avatar
  get '/avatar/:id', to: 'avatars#show', as: 'avatar'
  get 'home/index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/controller.rb
class Controller < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_one_attached :image
    has_many :comments
    has_many :reactions
    attribute :content, :text
  end

app/models/reaction.rb
class Reaction < ApplicationRecord
  belongs_to :post
  belongs_to :user
  belongs_to :comment
  validates :user_id, uniqueness: { scope: :post_id}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :avatar
  has_many :posts
  has_many :comments
  has_many :reactions

  def to_s
    self.email
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Otros códigos y configuraciones
  
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:avatar]) # Agrega :avatar a los parámetros permitidos para el registro
    end
  end
  

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
  def show
    # Buscar el usuario por su ID
    @user = User.find_by(id: params[:id])

    # Asegurarse de que se haya encontrado el usuario
    if @user
      # Obtener el avatar del usuario
      @avatar = @user.avatar

      # Asegurarse de que el usuario tenga un avatar adjunto
      if @avatar && @avatar.attached?
        # Enviar el avatar al navegador como tipo de contenido de imagen
        send_data @avatar.download, type: @avatar.content_type, disposition: 'inline'
      else
        # Si el usuario no tiene un avatar adjunto, redireccionar a una imagen de avatar predeterminada o manejar el error según tus necesidades
        redirect_to default_avatar_path
      end
    else
      # Si no se encontró el usuario, redireccionar a una imagen de avatar predeterminada o manejar el error según tus necesidades
      redirect_to default_avatar_path
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    
    before_action :current_user_logged

    def new
        @post = params[:post]
        @comment = Comment.new
    end
    
    def edit
    end

    def create
        @comment = Comment.new(comment_params)
        respond_to do |format|
            if @comment.save
                format.html { redirect_to root_path, notice: "El comentario ha sido añadido correctamente." }
            else
                format.html { render :new, status: :unprocessable_entity }
            end
        end
    end

    def update
        respond_to do |format|
            if @comment.update(comment_params)
              format.html { redirect_to root_path, notice: "El comentario ha sido actualizado correctamente." }
            else
              format.html { render :edit, status: :unprocessable_entity }
            end
        end
    end

    def destroy
        @comment.destroy
        respond_to do |format|
          format.html { redirect_to root_path, notice: "El comentario ha sido eliminado correctamente." }
        end
    end

    private

    def set_comment
        @comment = Comment.find(params[:id])
      end

    def comment_params
        params.require(:comment).permit(:content, :post_id).merge(user_id: current_user.id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        @posts = Post.includes(:comments)
        @posts = Post.all # Obtén todos los posts de la base de datos
        @post = Post.new  # Crea una nueva instancia de Post para el formulario de nueva publicación
        if user_signed_in?
            post_ids = @posts.pluck(:id)
            user_reactions = current_user.reactions.where(post_id: post_ids)
            @user_reactions = user_reactions.index_by(&:post_id)
        end
    end
end



  

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :set_post, only: [:edit, :update, :destroy]
    before_action :authorize_user, only: [:edit, :update, :destroy]
    before_action :current_user_logged, only: [:index, :new, :create, :edit, :update, :destroy]
  
    def index
      @posts = Post.all
    end
  
    def new
      @post = Post.new
    end
  
    def edit
    end
  
    def create
      @post = Post.new(post_params)
  
      respond_to do |format|
        if @post.save
          format.html { redirect_to root_path, notice: "Post was successfully created." }
          format.json { render :show, status: :created, location: @post }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    end
  
    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to root_path, notice: "Post was successfully updated." }
        else
          format.html { render :edit, status: :unprocessable_entity }
        end
      end
    end
  
    def destroy
      @post.destroy
      respond_to do |format|
        format.html { redirect_to root_path, notice: "Post was successfully destroyed." }
      end
    end
  
    private
    
    def authorize_user
      @post = Post.find(params[:id])
      unless @post.user == current_user
        flash[:alert] = "You are not authorized to perform this action."
        redirect_to root_path
      end
    end
  
    def set_post
      @post = Post.find(params[:id])
    end
  
    def post_params
      params.require(:post).permit(:content, :post_id, :title, :content, :image).merge(user_id: current_user.id)
    end
  
    def current_user_logged
      # Coloca aquí la lógica para verificar si el usuario está logueado
      # y redirige o realiza cualquier acción necesaria.
    end
  end
  

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController

    before_action :current_user

    def create
        @reaction = Reaction.new(reaction_params)
        @reaction = current_user.reactions.build(reaction_params)
        respond_to do |format|
            if @reaction.save
                format.html { redirect_to root_path, notice: "Reaction was successfully created." }
            else
                format.html { redirect_to root_path, status: :unprocessable_entity }
            end
        end
        
    end

    def destroy
        @reaction = current_user.reactions.find(params[:id])
        @reaction.destroy
        respond_to do |format|
            format.html { redirect_to root_path, notice: "Reaction was successfully destroyed." }
        end
    end

    private
  
    def reaction_params
      params.require(:reaction).permit(:post_id)
    end
end




  

app/controllers/users_controller.rb
class UsersController < ApplicationController
    # Resto del código del controlador
      has_one_attached :avatar
   

    def create
        @user = User.new(user_params)
    
        if @user.save
          redirect_to root_path, notice: 'Registro exitoso. ¡Bienvenido!'
        else
          render :new
        end
      end
    

    private
  
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar)
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/views/avatars/show.html.erb
<div class="container">
  <div class="row py-5">
    <div class="col-12 text-center">
      <h1><%= image_tag("navbar/logo", alt: "Logo", style: "width: 50px; height: 50px;") %> KariPic</h1>
      <p>Blog para compartir fotografías</p>
    </div>
  </div>

  <div class="row py-5">
    <div class="col-12 col-md-8 mx-auto">
      <div class="card mb-4">
        <div class="card-body">
          <h2>Avatar Profile</h2>
          <% if @user && @user.avatar.attached? %>
            <%= image_tag @user.avatar, class: "avatar-image" %>
          <% else %>
            <%= image_tag "default_avatar.jpg", class: "avatar-image" %>
          <% end %>
          <p><strong>Name:</strong> <%= @user.name %></p>
          <p><strong>Email:</strong> <%= @user.email %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p>
    <strong>Content:</strong>
    <%= comment.content %>
  </p>

  <p>
    <strong>User:</strong>
    <%= comment.user_id %>
  </p>

  <p>
    <strong>Post:</strong>
    <%= comment.post_id %>
  </p>

</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :content, "Contenido de tu comentario", style: "display: block", class: "form-label" %>
    <%= form.text_area :content, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.hidden_field :post_id, value: @post %>
  </div>

  <div class="mb-3">
    <%= form.submit "Agrega el comentario", class: "btn btn-success w-100" %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", comment %>
    </p>
  <% end %>
</div>

<%= link_to "New comment", new_comment_path %>

app/views/comments/new.html.erb
<div class="row py-5">
  <div class="col-12">
    <h1 class="text-center">Nuevo comentario</h1>
  </div>
</div>

<div class="row py-5">
  <div class="col-12">
    <%= render "form", comment: @comment %>
  </div>
</div>

<div class="row py-5">
  <div class="col-12">
    <%= link_to "Vuelve al inicio", root_path %>
  </div>
</div>

app/views/home/index.html.erb
<div class="container">
  <div class="row py-5">
    <div class="col-12 text-center">
      <h1><%= image_tag("navbar/logo", alt: "Logo", style: "width: 50px; height: 50px;" ) %> KariPic</h1>
      <p>Blog para compartir fotografías</p>
    </div>
  </div>

  <div class="row py-5">
    <div class="col-12 col-md-8 mx-auto">
      <% @posts.each do |post| %>
        <div class="card mb-4">
          <div class="comments">
            <% post.comments.each do |comment| %>
              <div class="comment mb-3">
                <%= comment.content %>
              </div>
            <% end %>
          </div>

          <div class="card">
            <% if post.image.attached? %>
              <div class="post-image">
                <%= image_tag post.image %>
              </div>
            <% end %>



  <!-- Mostrar la foto de perfil del usuario que realizó el post -->
  <% if post.user.avatar.attached? %>
    <div class="user-avatar" style="background-image: url('<%= url_for(post.user.avatar) %>');">
    </div>
  <% end %>
</div>




            <div class="card-body">
              <%= render post %>



            <div class="card-footer">
              <!-- Botones de comentar y me gusta -->
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <% if user_signed_in? %>
    <div class="row py-5">
      <div class="col-12 text-center d-flex justify-content-center mt-1">
        <%= link_to "Nueva publicación", new_post_path, class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KariPic</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <%= render 'shared/navbar' %>

  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: @post, url: posts_path, local: true) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, class: "form-control" %>
  </div>
 

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">

  <h2 class="text-center"><%= post.title %></h2>
  <p><%= post.content %></p>
  <p><strong>Autor: </strong><%= post.user.email if post.user %></p>


  <div class="row py-3">
    <span class="text-center">Han reaccionado <%= post.reactions.count %> personas</span>
  </div>

  <div class="row py-3">
    <div class="col-6">
        <%= link_to 'Comenta', "/comments/new?post=#{post.id}", class: 'btn btn-primary w-100' %>
    </div>

    <div class="col-6">
      <% if user_signed_in? %>
        <% reaction = current_user.reactions.find_by(post: post) %>
        <% if reaction.nil? %>
          <%= button_to "Me gusta", reactions_path, params: { reaction: { post_id: post.id } }, method: :post, class: "btn btn-secondary w-100" %>
        <% else %>
          <%= button_to "No me gusta", reaction_path(reaction), method: :delete, class: "btn btn-secondary w-100" %>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="row py-3">
    <% post.comments.each do |comment| %>
      <% if comment.user_id == 0 %>
        <p>Anónimo comenta: <%= comment.content %></p>
      <% else %>
        <p><%= comment.user.email %> comenta: <%= comment.content %></p>
      <% end %>
    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Publicaciones</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
      <% if post.user == current_user %>
        <%= link_to "Edit", edit_post_path(post) %>
        <%= link_to "Destroy", post, method: :delete, data: { confirm: "Are you sure you want to delete this post?" } %>
      <% end %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/reactions/_form.html.erb
<%= form_with(model: reaction) do |form| %>
<div class="row">
  <% if reaction.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(reaction.errors.count, "error") %> prohibited this reaction from being saved:</h2>
      <ul>
        <% reaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>  
</div>

<div class="row py-5">    
  <div class="col-4">
    <div class="form-check">
      <%= form.radio_button :reaction_type, :me_gusta, class: "form-check-input", checked: true %>
      <label class="form-check-label" for="model_reaction_type_opcion1">Me gusta</label>
    </div>
  </div>
  <div class="col-4">
    <div class="form-check">
      <%= form.radio_button :reaction_type, :sin_reaccion, class: "form-check-input" %>
      <label class="form-check-label" for="model_reaction_type_opcion1">Sin reacción</label>
    </div>
  </div>
  <div class="col-4">
    <div class="form-check">
      <%= form.radio_button :reaction_type, :no_me_gusta, class: "form-check-input" %>
      <label class="form-check-label" for="model_reaction_type_opcion1">No me gusta</label>
    </div>
  </div>
</div>



<div class="row">
  <div class="mb-3">
    <%= form.hidden_field :post_id, value: @post %>
  </div>
  <div class="mb-3">
    <%= form.submit "Agrega la reacción", class: "btn btn-success w-100" %>
  </div>
</div>
<% end %>

app/views/reactions/_reaction.html.erb
<div id="<%= dom_id reaction %>">
  <p>
    <strong>Reaction type:</strong>
    <%= reaction.reaction_type %>
  </p>

  <p>
    <strong>User:</strong>
    <%= reaction.user_id %>
  </p>

  <p>
    <strong>Post:</strong>
    <%= reaction.post_id %>
  </p>

</div>

app/views/reactions/edit.html.erb
<h1>Editing reaction</h1>

<%= render "form", reaction: @reaction %>

<br>

<div>
  <%= link_to "Show this reaction", @reaction %> |
  <%= link_to "Back to reactions", reactions_path %>
</div>

app/views/reactions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Reactions</h1>

<div id="reactions">
  <% @reactions.each do |reaction| %>
    <%= render reaction %>
    <p>
      <%= link_to "Show this reaction", reaction %>
    </p>
  <% end %>
</div>

<%= link_to "New reaction", new_reaction_path %>

app/views/reactions/new.html.erb
<div class="row py-5">
  <div class="col-12">
    <h1 class="text-center">Reacción</h1>
  </div>
</div>

<div class="row py-5">
  <div class="col-12">
    <%= render "form", reaction: @reaction %>
  </div>
</div>

<div class="row py-5">
  <div class="col-12">
    <%= link_to "Vuelve al Inicio", reactions_path %>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer style="background-color: black; color: white;">
    <div class="container">
        <div class="row py-5">
            <h4 class="text-center py-3"><%= image_tag("navbar/logo", alt: "Logo", style: "width: 50px; height: 50px;" ) %>  Crazy 4 Cats</h4>
            <div class="col-6">
                <p>Contacto</p>
                <ul>
                    <li>+61584845485</li>
                    <li>crazy4cats_contacto@gmail.cl</li>
                </ul>
            </div>
            <div class="col-6">
                <p>Dirección:</p>
                <ul>
                    <li>734 Main st</li>
                    <li>Australia, kangaaropoint</li>
                </ul>
            </div>
            <h4 class="text-center py-5">Todos los derechos reservados para rodrigo salgado.</h4>
        </div>
    </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-dark bg-dark">
  <div class="container">
    <div class="d-flex">
      <button class="btn navbar-brand btn-lg" type="button" onclick="location.href='/';">
        <%= image_tag("navbar/logo", alt: "Logo", style: "width: 50px; height: 50px;") %> KariPic
      </button>
      <a class="navbar-brand ms-2" href="/posts">
        <button type="button" class="btn btn-outline-light btn-lg">Publicaciones</button>
      </a>
    </div>

    <div class="navbar-collapse-container">
      <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse"
        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
        aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button"
              data-bs-toggle="dropdown" aria-expanded="false">
              <% if user_signed_in? %>
              <i class="fa-solid fa-user"></i> Bienvenido/a <%= current_user.email %>
              <% else %>
              <i class="fa-solid fa-user-secret"></i> Inicia sesión
              <% end %>
            </a>
            <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
              <% if user_signed_in? %>
              <li><%= button_to 'Cerrar sesión', destroy_user_session_path, class: 'dropdown-item', method: :delete %></li>
              <li><%= link_to 'Ver avatar', avatar_path(current_user.id), class: 'dropdown-item' %></li>
              <% else %>
              <li><%= link_to 'Iniciar sesión', new_user_session_path, class: 'dropdown-item' %></li>
              <li><hr class="dropdown-divider" style="border-top: 1px solid #fff;"></li>
              <li><%= link_to 'Registro', new_user_registration_path, class: 'dropdown-item' %></li>
              <% end %>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>